### ISSUE TITLE
Hello theme missing Console and Flush Console menu icons

### ISSUE THREAD

**Issue by pcwalden** [meradoou/hello#3]
With the Hello theme, on the Console page. The two page header menu buttons are blank.

Suggest the follow adds to themes/hello/css/app.css

@@ -312,6 +312,10 @@ section.page {
content: "\f0ec"; }
.page-header ul li a[href*="action=refresh-feed"]:after {
content: "\f021"; }

```
.page-header ul li a[href="?action=console"]:after {
content: "\f085"; }
.page-header ul li a[href="?action=flush-console"]:after {
content: "\f014"; }
```

**Comment by miradozk** [comment]
@pcwalden  Fixed
