### ISSUE TITLE
Miniflux has changed and Hello theme hides some features

### ISSUE THREAD

**Issue by pcwalden** [meradoou/hello#4]
With the latest set of miniflux changes, some of its features are not showing in the Hello theme:
- bottom_menu that shows the mark-all-read on the item list pages is missing
- bookmark and remove bookmark menu commands no longer show a bookmar star against the item article
- the feed error messages are now turned on via CSS by a _data-feed-error_ attribute added to the article tag.The result is that all feeds are showing as having an error on the subscription page. See miniflux issue [#310](https://github.com/fguillot/miniflux/issues/310)

**Comment by miradozk** [comment]
I fixed the bottom_menu (mark-all-read) and reverse the bookmark icon. For  the feed error, I don't understand the bug.
