### ISSUE TITLE
Enhancement request to use new classes for enclosures

### ISSUE THREAD

**Issue by pcwalden** [meradoou/hello#5]
fguillot added class attributes to the enclosure menu items in [templates/items.php](https://github.com/miniflux/miniflux/blob/master/templates/item.php). Enclosure type icons can now be added to the "attachment" menu item. I have a suggestion below. I find these icons easily identify whether the attachment is a video or audio type.

```
.items .item-menu li a.video-enclosure:before { content: "\f1c8"; }
.items .item-menu li a.audio-enclosure:before { content: "\f1c7"; }
.items .item-menu li a.image-enclosure:before { content: "\f1c5"; }
.items .item-menu li a.enclosure:before { content: "\f15b"; }
```

**Comment by miradozk** [comment]
Fixed

**Comment by pcwalden** [comment]
Thanks!
