### ISSUE TITLE
item  attachment menu link no longer has video-enclosure icon showing

### ISSUE THREAD

**Issue by pcwalden** [meradoou/hello#7]
I have not updated my miniflux instance for awhile, but with the recent update, the video icon in the item menu attachment link is no longer showing.

The link is <a class="video-enclosure" .. href=..>attachment</a>
The ::before is not being inserted.

**Comment by miradozk** [comment]
J'ai corrigé l'icone sur branche master. 
A noter que je utilise la version disponible sur branche reader donc les 2 autres branches ne sont plus mis à jour en cas d'erreur.

**Comment by pcwalden** [comment]
merci!
